db:
  image: produban/introscope-postgresql:9.7

introscope:
  image: stefansiegl/introscope-em
  links:
   - db:db
  ports:
   - "5001:5001"
   - "8081:8081"
   - "8080:8080"
  environment:
   - HEAP="1024m"
